######################################################################
# Automatically generated by qmake (3.1) Mon Nov 30 13:42:14 2020
######################################################################

TEMPLATE = app
TARGET = simple
INCLUDEPATH += .

# Input
SOURCES += simple.cpp

QT += widgets
